### PR TITLE
Support for drawing 8bpp alpha masks.

### PR DESCRIPTION
**Pull request by jpap**
This PR adds support for drawing to an 8bpp (greyscale) canvas, suitable for creating alpha masks.

Somewhat related to #44, this PR may also be helpful as the basis for other "painter modes" in the future.

I'm using this for another project and am very happy to make any required changes to see it land.

### CODE REVIEW

**Comment by jpap** [comment]
Hey @fogleman, would love to get your feedback on this one. :)

**Comment by fogleman** [comment]
Thanks for the PR.

Really, it'd be nice if `gg` supported other backends like RGBA64, etc. This might be better for a v2 of gg. For now I'm not comfortable merging such a large change.

**Comment by jpap** [comment]
That's unfortunate, but understandable.  I'll keep working from a fork.  Thanks for considering the PR!

**Comment by fogleman** [comment]
Sorry to disappoint, but thanks for understanding.

**Pull request closed without merging**
