### PR TITLE
default fill/stroke (black on white)

### PR DESCRIPTION
**Pull request by wsw0108**

### CODE REVIEW

**Comment by wsw0108** [comment]
To avoid problem when call `dc.Fill()` or `dc.Stroke()` without set fill/stroke before.

**Comment by wsw0108** [comment]
Thanks, for your work!

**Comment by fogleman** [comment]
@wsw0108 Now that we have `patternPainter`, I think we can add a mask to it and greatly improve the performance of clipping operations. What do you think?

**Comment by fogleman** [comment]
@wsw0108 It is done: https://github.com/fogleman/gg/commit/bc0c0e9e67a20a5e33d93e4e51302f946f8d5583

**Pull request merged**
