### PR TITLE
Implement PlotXY widget to draw line charts

### PR DESCRIPTION
**Pull request by cpmech**
Hi,

I've implemented a tool to easily draw line graphs with `gg`. For example, using something like:

```
p := gg.NewPlotXY()
c := p.AddCurve("data", []float64{1, 2, 3, 4}, []float64{1, 4, 9, 16})
dc := gg.NewContext(400, 300)
p.Render(dc)
dc.SavePNG("/tmp/figure-simple.png")
```

Here you are some output

figure-simple

figure

Cheers.
Dorival

### CODE REVIEW

**Comment by fogleman** [comment]
Very cool @cpmech !

I recommend making this a separate package / repo for producing charts in Go. Of course, it can be built on top of `gg`. Have you considered this approach?

**Comment by cpmech** [comment]
Thanks!

Yes, I have considered making this a separate package; e.g. maybe within the `plt` subpackage of https://github.com/cpmech/gosl

However, I thought this widget would fit `gg` better because:

1. there are just two files using `gg` only
3. `gg` is easy to `go get` compared to `gosl`
2. there are many other Go packages around already
3. `gg` is great, simple, and may benefit or a simple plotting tool
4. I don't expect to PlotXY becoming a large tool for producing charts...

**Comment by peterhellberg** [comment]
@cpmech Do you consider the code in this PR to be licensed under the MIT license? (Thinking about making a separate package heavily based on your code)

**Comment by cpmech** [comment]
Yes! Please go ahead

**Comment by peterhellberg** [comment]
@cpmech A small preview: https://gist.github.com/peterhellberg/02edda037819301dd64cf063e6616bd5

pixel-ggplot

**Pull request closed without merging**
